"""Member DTOs + ORM->DTO mapper."""

from __future__ import annotations

from datetime import date

from app.core.base.dto import BaseDTO
from app.modules.members.models.member import Member


class CreateMemberRequest(BaseDTO):
    first_name: str
    last_name: str | None = None
    phone: str | None = None
    email: str | None = None
    national_id: str | None = None
    gender: str | None = None
    birth_date: date | None = None
    address: str | None = None
    notes: str | None = None
    #: Optional; auto-generated by the service when omitted.
    membership_number: str | None = None


class MemberDTO(BaseDTO):
    id: int
    uuid: str
    membership_number: str
    first_name: str
    last_name: str | None = None
    full_name: str
    phone: str | None = None
    email: str | None = None
    national_id: str | None = None
    gender: str | None = None
    birth_date: date | None = None
    address: str | None = None
    notes: str | None = None
    is_active: bool = True


def to_member_dto(member: Member) -> MemberDTO:
    return MemberDTO(
        id=member.id,
        uuid=member.uuid,
        membership_number=member.membership_number,
        first_name=member.first_name,
        last_name=member.last_name,
        full_name=member.full_name,
        phone=member.phone,
        email=member.email,
        national_id=member.national_id,
        gender=member.gender,
        birth_date=member.birth_date,
        address=member.address,
        notes=member.notes,
        is_active=member.is_active,
    )
